import { ROL } from "../src/domain/entities/user-entity";

export const userList = [
  { firstName: "Antonio", lastName: "Perez", email: "antonio@gmail.com", password: "12345678", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/50.jpg" },
  { firstName: "Lara ", lastName: "Alcaráz", email: "lara@gmail.com", password: "87654321", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/51.jpg" },
  { firstName: "Leon ", lastName: "López", email: "leon@gmail.com", password: "0fsdf0000", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/52.jpg" },
  { firstName: "Virginia ", lastName: "Alonso", email: "virg@gmail.com", password: "1ads11111", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/53.jpg" },
  { firstName: "Antonio", lastName: "Perez", email: "antonio2@gmail.com", password: "1da45678", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/54.jpg" },
  { firstName: "Juan", lastName: "Gonzalez", email: "juan.gonzalez@example.com", password: "qwefsdrty123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/55.jpg" },
  { firstName: "Luis", lastName: "Ramirez", email: "luis.ramirez@example.com", password: "ilovecats", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/56.jpg" },
  { firstName: "Carlos", lastName: "Hernandez", email: "carlos.hernandez@example.com", password: "football23", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/57.jpg" },
  { firstName: "Javier", lastName: "Lopez", email: "javier.lopez@example.com", password: "welcome123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/58.jpg" },
  { firstName: "Daniel", lastName: "Torres", email: "daniel.torres@example.com", password: "password123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/59.jpg" },
  { firstName: "Miguel", lastName: "Gomez", email: "miguel.gomez@example.com", password: "abcde123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/60.jpg" },
  { firstName: "Jose", lastName: "Morales", email: "jose.morales@example.com", password: "hello123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/61.jpg" },
  { firstName: "Alejandro", lastName: "Castillo", email: "alejandro.castillo@example.com", password: "test232123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/62.jpg" },
  { firstName: "Francisco", lastName: "Ortega", email: "francisco.ortega@example.com", password: "letmersewin", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/63.jpg" },
  { firstName: "Pedro", lastName: "Vargas", email: "pedro.vargas@example.com", password: "1234s2356", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/64.jpg" },
  { firstName: "Manuel", lastName: "Salazar", email: "manuel.salazar@example.com", password: "pas32sword", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/65.jpg" },
  { firstName: "Hugo", lastName: "Cortes", email: "hugo.cortes@example.com", password: "qwer232ty", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/66.jpg" },
  { firstName: "Roberto", lastName: "Valenzuela", email: "roberto.valenzuela@example.com", password: "ab232c123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/67.jpg" },
  { firstName: "Ricardo", lastName: "Vargas", email: "ricardo.vargas@example.com", password: "ilosveyou", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/68.jpg" },
  { firstName: "Arturo", lastName: "Fuentes", email: "arturo.fuentes@example.com", password: "welfssdfcome", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/69.jpg" },
  { firstName: "Enrique", lastName: "Molina", email: "enrique.molina@example.com", password: "123afsdfbc", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/70.jpg" },
  { firstName: "Adrian", lastName: "Rojas", email: "adrian.rojas@example.com", password: "testin23g123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/71.jpg" },
  { firstName: "Fernando", lastName: "Cruz", email: "fernando.cruz@example.com", password: "passs1fs23", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/72.jpg" },
  { firstName: "Sergio", lastName: "Pacheco", email: "sergio.pacheco@example.com", password: "qwertyuiop", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/73.jpg" },
  { firstName: "Guillermo", lastName: "Acosta", email: "guillermo.acosta@example.com", password: "1234567890", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/74.jpg" },
  { firstName: "Emilio", lastName: "Nava", email: "emilio.nava@example.com", password: "testt23est", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/75.jpg" },
  { firstName: "Andrés", lastName: "Cervantes", email: "andres.cervantes@example.com", password: "passsword1234", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/76.jpg" },
  { firstName: "Roberto", lastName: "Santos", email: "roberto.santos@example.com", password: "abcde12345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/77.jpg" },
  { firstName: "Eduardo", lastName: "Rivas", email: "eduardo.rivas@example.com", password: "hello12345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/78.jpg" },
  { firstName: "Gustavo", lastName: "Delgado", email: "gustavo.delgado@example.com", password: "test12345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/79.jpg" },
  { firstName: "Ramiro", lastName: "Cano", email: "ramiro.cano@example.com", password: "letmein123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/80.jpg" },
  { firstName: "Roberto", lastName: "Vera", email: "roberto.vera@example.com", password: "123sff4567", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/81.jpg" },
  { firstName: "Martín", lastName: "Cabrera", email: "martin.cabrera@example.com", password: "passsword123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/82.jpg" },
  { firstName: "Julio", lastName: "Navarro", email: "julio.navarro@example.com", password: "qwerty1234", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/83.jpg" },
  { firstName: "Héctor", lastName: "Guerrero", email: "hector.guerrero@example.com", password: "ilovecats123", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/84.jpg" },
  { firstName: "Samuel", lastName: "Paredes", email: "samuel.paredes@example.com", password: "football234", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/85.jpg" },
  { firstName: "Raul", lastName: "Mendoza", email: "raul.mendoza@example.com", password: "welcome1234", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/86.jpg" },
  { firstName: "Jorge", lastName: "Escobar", email: "jorge.escobar@example.com", password: "password12345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/87.jpg" },
  { firstName: "Agustín", lastName: "Rosas", email: "agustin.rosas@example.com", password: "abcde123456", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/88.jpg" },
  { firstName: "Maximiliano", lastName: "Castañeda", email: "maximiliano.castaneda@example.com", password: "hello123456", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/89.jpg" },
  { firstName: "Salvador", lastName: "Velasco", email: "salvador.velasco@example.com", password: "test123456", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/90.jpg" },
  { firstName: "Alberto", lastName: "Romo", email: "alberto.romo@example.com", password: "letmein1234", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/91.jpg" },
  { firstName: "Jaime", lastName: "Franco", email: "jaime.franco@example.com", password: "12345678", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/92.jpg" },
  { firstName: "Rubén", lastName: "Mendez", email: "ruben.mendez@example.com", password: "passsword1234", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/93.jpg" },
  { firstName: "Felipe", lastName: "Montes", email: "felipe.montes@example.com", password: "qwerty12345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/94.jpg" },
  { firstName: "Benjamín", lastName: "Pineda", email: "benjamin.pineda@example.com", password: "ilovecats1234", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/95.jpg" },
  { firstName: "Oscar", lastName: "Valencia", email: "oscar.valencia@example.com", password: "football2345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/96.jpg" },
  { firstName: "Rogelio", lastName: "Beltrán", email: "rogelio.beltran@example.com", password: "welcome12345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/97.jpg" },
  { firstName: "César", lastName: "Palacios", email: "cesar.palacios@example.com", password: "password12345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/98.jpg" },
  { firstName: "Leonardo", lastName: "Arroyo", email: "leonardo.arroyo@example.com", password: "abcde1234567", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/99.jpg" },
  { firstName: "Mario", lastName: "Fuentes", email: "mario.fuentes@example.com", password: "hello1234567", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/20.jpg" },
  { firstName: "Giovanni", lastName: "Carrasco", email: "giovanni.carrasco@example.com", password: "test1234567", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/21.jpg" },
  { firstName: "Diego", lastName: "Olvera", email: "diego.olvera@example.com", password: "letmein12345", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/22.jpg" },
  { firstName: "Israel", lastName: "Amador", email: "israel.amador@example.com", password: "123456789", rol: ROL.PLAYER, image: "https://randomuser.me/api/portraits/men/23.jpg" },
  { firstName: "Ernesto ", lastName: "Sevilla", email: "ernesczxato@gmail.com", password: "22222dsf222", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/24.jpg" },
  { firstName: "Ernesto", lastName: "Sevilla", email: "ernescxdto@gmail.com", password: "22222f222", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/25.jpg" },
  { firstName: "Javier", lastName: "García", email: "javier.garcia@example.com", password: "12345678", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/26.jpg" },
  { firstName: "Luis", lastName: "Fernández", email: "luis.fernandez@example.com", password: "password123", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/27.jpg" },
  { firstName: "Roberto", lastName: "Mendoza", email: "roberto.mendoza@example.com", password: "qwerty123", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/28.jpg" },
  { firstName: "Carlos", lastName: "Martínez", email: "carlos.martinez@example.com", password: "ilovecats", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/29.jpg" },
  { firstName: "Juan", lastName: "Hernández", email: "juan.hernandez@example.com", password: "abcdefg23", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/30.jpg" },
  { firstName: "Ana ", lastName: "Obregón", email: "ana@gmail.com", password: "33333333", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/31.jpg" },
  { firstName: "Francisco ", lastName: "Bueno", email: "frank@gmail.com", password: "44444444", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/32.jpg" },
  { firstName: "Toni ", lastName: "Moreno", email: "toni@gmail.com", password: "55555555", rol: ROL.MANAGER, image: "https://randomuser.me/api/portraits/men/33.jpg" },
  { firstName: "Antonio", lastName: "Alcaráz", email: "admin@gmail.com", password: "55555555", rol: ROL.ADMIN, image: "https://randomuser.me/api/portraits/men/34.jpg" },
];

export const teamList = [
  { name: "Real Madrid CF", initials: "RMC", image: "https://assets.laliga.com/assets/2019/06/07/small/real-madrid.png" },
  { name: "Barcelona FC", initials: "FBC", image: "https://assets.laliga.com/assets/2019/06/07/small/barcelona.png" },
  { name: "Cadiz FC", initials: "CDF", image: "https://assets.laliga.com/assets/2019/06/07/small/cadiz.png" },
  { name: "Real Betis", initials: "RBC", image: "https://assets.laliga.com/assets/2022/09/15/small/e4a09419d3bd115b8f3dab73d480e146.png" },
  { name: "Sevilla FC", initials: "SFC", image: "https://assets.laliga.com/assets/2019/06/07/small/sevilla.png" },
  { name: "Valencia CF", initials: "VCF", image: "https://assets.laliga.com/assets/2019/06/07/small/valencia.png" },
  { name: "Real Sociedad", initials: "RSC", image: "https://assets.laliga.com/assets/2019/06/07/small/real-sociedad.png" },
  { name: "Atlético de Madrid", initials: "ATM", image: "https://assets.laliga.com/assets/2019/06/07/small/atletico.png" },
  { name: "Girona FC", initials: "GFC", image: "https://assets.laliga.com/assets/2019/06/07/small/girona.png" },
  { name: "Getafe FC", initials: "GEC", image: "https://assets.laliga.com/assets/2019/06/07/small/getafe.png" },
]
